### PR TITLE
implements multiple puppet directories

### PR DESCRIPTION
**Pull request by endyman**
Implements multi puppet directory support.

### CODE REVIEW

**Comment by mhahn** [comment]
@endyman can you add a test for this?

ie. so when running `bundle exec vagrant up` i can verify that it works properly?

**Comment by endyman** [comment]
@mhahn the current implementation supports both cases, a string or an array as value for `librarian_puppet.puppetfile_dir` so if I'm going to change the value in Vagrantfile into an array and add a second puppet folder + Puppetfile we just test the multi directory (array) case if we execute `bundle exec vagrant up`.

What I could do is to create a second box to cover the multi directory (array) case.

Regarding the current implementation what is your opinion? I decided not to introduce a new config_key for the array use-case (to match the `puppet.module_path` implementation).  The alternative would be to introduce a config_key for the multi directory (array) case i.e. `librarian_puppet.puppetfile_dirs`.

**Comment by mhahn** [comment]
+1 to the second box.

i think the implementation looks great!

**Comment by endyman** [comment]
@mhahn I added a dedicated box and a second puppet dir. In Addition I added .gitkeep files in order to not run into the non existing modules dir error right after cloning this repo. (Modules provisioned to the modules dirs are still ignored via gitignore)

**Pull request merged**
